export const DEPT_MAP: Record<string, { dept: string }> = {
  AMSC: { dept: 'Applied Mathematics and Scientific Computing' },
  AR: { dept: 'Architecture and Planning' },
  BSBE: { dept: 'Biosciences and Bioengineering' },
  CH: { dept: 'Chemical Engineering' },
  CY: { dept: 'Chemistry' },
  CE: { dept: 'Civil Engineering' },
  CSE: { dept: 'Computer Science and Engineering' },
  DES: { dept: 'Design' },
  EQ: { dept: 'Earthquake Engineering' },
  ES: { dept: 'Earth Sciences' },
  EE: { dept: 'Electrical Engineering' },
  ECE: { dept: 'Electronics and Communication Engineering' },
  HSS: { dept: 'Humanities and Social Sciences' },
  HYD: { dept: 'Hydrology' },
  HRE: { dept: 'Hydro and Renewable Energy' },
  DOMS: { dept: 'Management Studies' },
  MA: { dept: 'Mathematics' },
  MEID: { dept: 'Mechanical and Industrial Engineering' },
  META: { dept: 'Metallurgical and Materials Engineering' },
  PT: { dept: 'Paper and Packaging Technology' },
  POLY: { dept: 'Polymer and Process Engineering' },
  PH: { dept: 'Physics' },
  WRD: { dept: 'Water Resources Development and Management' }
};
